image: python:2.7

stages:
  - test
  - build
  - deploy_to_dev
  - test_on_dev
  - deploy_to_uat
  - deploy_to_prod

cache:
  paths:
    - assembl/static2/node_modules/
    - /usr/local/share/.cache/yarn/v2

test_frontend:
  stage: test
  except:
    - master
    - tmp_master_for_ci_cd
    - add_deploy_job
  image: node:10
  before_script:
    - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - cd assembl/static2
    - yarn
  script:
    # This will fail if any test fails or if the coverage has lowered
    - yarn jest --coverage --maxWorkers 2
    - yarn run eslint
    - yarn run stylelint
    - yarn run flow --quiet

test_integration_and_ui:
  stage: test_on_dev
  image: node:10
  only:
    - tmp_master_for_ci_cd
    - add_deploy_job
  before_script:
    - eval $(ssh-agent -s) && sh scripts/configure_ssh.sh
    - sh scripts/prepare_integration_tests.sh
  script:
    # run integration tests
    - yarn jest tests/integration
    # run each ui test one by one
    - yarn runinband

build_wheel:
  stage: build
  only:
    - develop
    - add_deploy_job
  variables:
    DEVELOP_BRANCH: develop
    MASTER_BRANCH: tmp_master_for_ci_cd
  artifacts:
    paths:
      - dist/
  variables:
    DEPLOYING: true
  before_script:
    - sh scripts/install_build_dependencies.sh
    - sh scripts/install_node_and_yarn.sh
    - sh scripts/configure_assembl_remote.sh
    - sh scripts/configure_ssh.sh
    - sh scripts/clear_apt_cache.sh
    - pip install fabric==1.14
  script:
    # create the wheel and upload to pypi
    - sh scripts/create_assembl_wheel.sh
    # - twine upload -u bluenove --skip-existing dist/*
    - fab -f $CI_PROJECT_DIR/assembl/configs/local_prod.rc create_wheelhouse
    - fab -f $CI_PROJECT_DIR/assembl/configs/aws.rc push_wheelhouse:house="s3://bluenove-assembl-wheelhouse"
    - fab -f $CI_PROJECT_DIR/assembl/configs/aws.rc push_client_themes:house="s3//bluenove-client-themes"
    # Remove ssh files so that the keys are not kept on image prior to travis removal
    - rm -rf ~/.ssh


push_to_develop_server:
  stage: deploy_to_dev
  only:
    - tmp_master_for_ci_cd
    - add_deploy_job
  variables:
    DEPLOYING: true
  before_script:
    - sh scripts/configure_ssh.sh
    - pip install fabric==1.14
    - mkdir -p private_configs
    - ssh -4 -i ~/.ssh/vaultmaster.pem vaultmaster@dev-assembl.bluenove.com "cd /opt/vault/bluenove-server-configs; git pull"
    - scp -4 -i ~/.ssh/vaultmaster.pem vaultmaster@dev-assembl.bluenove.com:/opt/vault/bluenove-server-configs/dev_staging.rc ./private_configs/dev_staging.rc
    - scp -4 -i ~/.ssh/vaultmaster.pem vaultmaster@dev-assembl.bluenove.com:/opt/vault/bluenove-server-configs/bluenove.rc ./private_configs/bluenove.rc
    - export VERSION=$(grep current_version .bumpversion.cfg | tr -d ' ' | awk -F "=" '{print $2}')
  script:
    - fab -f assembl/fabfile.py -c private_configs/dev_staging.rc deploy_wheel:$VERSION
    - fab -f assembl/fabfile.py -c private_configs/dev_staging.rc bootstrap_from_wheel

deploy_to_uat:
  stage: deploy_to_uat
  only:
    - tmp_master_for_ci_cd
    - add_deploy_job
  variables:
    DEPLOYING: true
  script:
    # empty script for now
    - echo "Running deployment..."

deploy_to_prod:
  stage: deploy_to_prod
  environment: PROD
  variables:
    DEPLOYING: true
  only:
    - tmp_master_for_ci_cd
  script:
    # fake script for now
    - python scripts/deploy_to_prod.py
  when: manual
